import { createContext, useContext, useRef, useState, useEffect } from 'react';
import { ArrowLeftIcon, ArrowRightIcon, CheckIcon, ChevronDownIcon, ImageIcon, Link2Icon, MagnifyingGlassIcon, PlusIcon, TextIcon } from '@radix-ui/react-icons';
import { BottomSheet, FlowStack, KeyboardInput, KeyboardTextarea, MobileScroll, useFlow, type FlowScreen } from './mobile';

type Kind='photo'|'text'|'link'; type Item={id:string;title:string;kind:Kind;note:string;room:number|null;image?:string;text?:string;url?:string;demo?:boolean};
const a=(name:string)=>`/museum/${name}`;
const rooms=[
 {id:1,name:'고요한 순간들',desc:'사진과 음악, 문장으로 모은 고요한 취향',media:'사진 · 음악 · 문장',image:'quiet-door.png'},
 {id:2,name:'언젠가의 공간',desc:'언젠가 머물고 싶은 공간을 모았습니다.',media:'공간 · 가구 · 생활의 온도',image:'lobby.png'},
 {id:3,name:'오래 곁에 둔 것들',desc:'물건에 남은 시간과 기억을 모았습니다.',media:'물건 · 사진 · 기억',image:'highlight.png'},
 {id:4,name:'아직 이름 없는 취향',desc:'이유를 몰라도 좋아하는 마음부터.',media:'음악 · 글 · 그리고 더 많은 것들',image:'album.png'},
];
const seed:Item[]=[
 {id:'rain',title:'비가 머물던 오후',kind:'photo',image:a('rain.png'),note:'창가에 앉아 아무것도 하지 않았던 시간.',room:1,demo:true},
 {id:'music',title:'창가의 선율',kind:'link',image:a('album.png'),note:'비 오는 오후에 어울리는 느린 선율.',room:1,demo:true},
 {id:'words',title:'서두르지 않아도 좋은 순간',kind:'text',text:'서두르지 않아도\n좋은 순간이 있다.',note:'오늘의 나에게 남기는 말.',room:1,demo:true},
 {id:'space',title:'빛이 머무는 자리',kind:'photo',image:a('lobby.png'),note:'아침 햇살이 길게 들어오는 집에서 살고 싶다.',room:2,demo:true},
 {id:'cup',title:'늘 손이 가던 컵',kind:'photo',image:a('highlight.png'),note:'아침마다 가장 먼저 꺼내는 컵. 조금 무겁고 투박하지만 하루가 천천히 시작된다.',room:3,demo:true},
 {id:'memory',title:'오래 기억하고 싶은 말',kind:'text',text:'좋아하는 것이 있다는 건\n오늘도 잘 살 만하다는 뜻이다.',note:'작고 평범한 순간들을 잊지 않기로.',room:3,demo:true},
 {id:'moon',title:'푸른 밤의 색',kind:'photo',image:a('album.png'),note:'무엇 때문인지는 아직 모르겠지만, 이 푸른색이 좋다.',room:4,demo:true},
];
const initial=[...seed,...seed.slice(0,4).map((x,i)=>({...x,id:`inbox-${i}`,room:null}))];
type State={items:Item[];add:(x:Item)=>void;place:(ids:string[],room:number)=>void;toast:(s:string)=>void}; const C=createContext<State|null>(null); const useMuseum=()=>useContext(C)!; const n=(x:number)=>String(x).padStart(2,'0');

function Header({title,home=false,dark=false}:{title?:string;home?:boolean;dark?:boolean}){const f=useFlow();return <header className={`museum-header ${dark?'dark':''}`}>{home?<strong>나의 취향 박물관</strong>:<button onClick={()=>f.replace(lobby())}><ArrowLeftIcon/> 로비로</button>}{title?<span>{title}</span>:<button onClick={()=>f.push(map())}>안내도 <ArrowRightIcon/></button>}</header>}
const lobby=():FlowScreen=>({id:'lobby',headerHeight:52,header:()=> <Header home/>,render:()=> <Lobby/>}); const map=():FlowScreen=>({id:'map',headerHeight:52,header:()=> <Header title="전시실 안내도"/>,render:()=> <Map/>}); const gallery=(id:number):FlowScreen=>({id:`gallery-${id}`,headerHeight:52,header:()=> <Header dark={id===3}/>,render:()=> <Gallery id={id}/>}); const inbox=():FlowScreen=>({id:'inbox',headerHeight:52,header:()=> <Header title="수집함"/>,render:()=> <Inbox/>}); const add=():FlowScreen=>({id:'add',headerHeight:52,header:f=><header className="museum-header"><button onClick={()=>f.pop()}>취소</button><span>소장품 추가</span><i/></header>,render:()=> <Add/>});

export default function Prototype(){const [items,setItems]=useState(initial);const [toast,setToast]=useState('');useEffect(()=>{if(!toast)return;const timer=setTimeout(()=>setToast(''),3000);return()=>clearTimeout(timer)},[toast]);return <C.Provider value={{items,add:x=>setItems(v=>[...v,x]),place:(ids,r)=>setItems(v=>v.map(x=>ids.includes(x.id)?{...x,room:r}:x)),toast:setToast}}><div className="museum-app"><FlowStack initial={lobby()}/>{toast&&<div className="museum-toast" role="status">{toast}</div>}</div></C.Provider>}
function Lobby(){const f=useFlow();const {items}=useMuseum();return <MobileScroll className="museum-scroll"><main className="lobby"><section className="lobby-hero" style={{backgroundImage:`url(${a('lobby.png')})`}}><small>나만의 공간</small><h1>취향이<br/>머무는 방</h1><p>마음에 남은 것들을 천천히 둘러보세요.</p></section><div className="lobby-tools"><h2>전시실</h2><button onClick={()=>f.push(inbox())}>수집함 <b>{items.filter(x=>x.room===null).length}</b></button><button onClick={()=>f.push(add())}><PlusIcon/> 소장품</button></div>{rooms.map(r=><article className="room-entry" key={r.id}><div className="room-caption"><span>{n(r.id)} {r.id===3&&<em>하이라이트</em>}</span><h2>{r.name}</h2><p>{r.media}</p></div><button className="door-button" onClick={()=>f.push(gallery(r.id))}><img src={a(r.image)} alt=""/><strong>입장하기 <ArrowRightIcon/></strong></button></article>)}</main></MobileScroll>}
function Plan({selected,onSelect}:{selected:number;onSelect:(n:number)=>void}){return <div className="map-art"><img src={a('floorplan.png')} alt="네 전시실 안내도"/>{rooms.map(r=><button key={r.id} className={`map-room r${r.id} ${selected===r.id?'selected':''}`} onClick={()=>onSelect(r.id)} aria-label={`${r.name} 선택`}><b>{n(r.id)}</b></button>)}</div>}
function Map(){const f=useFlow();const [selected,setSelected]=useState(1);const [zoom,setZoom]=useState(false);const r=rooms[selected-1];return <><MobileScroll className="museum-scroll"><main className="map-page pad"><div className="page-heading center"><h1>마음이 향하는 방으로</h1><p>전시실을 선택해 둘러보세요.</p></div><Plan selected={selected} onSelect={setSelected}/><button className="zoom-button" onClick={()=>setZoom(true)}><MagnifyingGlassIcon/> 크게 보기</button><div className="map-legend">{rooms.map(x=><button className={selected===x.id?'selected':''} onClick={()=>setSelected(x.id)} key={x.id}>{n(x.id)}　{x.name}</button>)}</div><section className="selected-room"><small>{n(r.id)} · {r.id===3?'하이라이트':'일반 전시'}</small><h2>{r.name}</h2><p>{r.desc}</p><img src={a(r.image)} alt=""/><button className="primary" onClick={()=>f.push(gallery(selected))}>이 전시실로 입장 <ArrowRightIcon/></button></section></main></MobileScroll><BottomSheet open={zoom} onOpenChange={setZoom} title="전시실 안내도" snap={.82}><Plan selected={selected} onSelect={setSelected}/><button className="primary" onClick={()=>setZoom(false)}>선택 완료 <CheckIcon/></button></BottomSheet></>}
function Gallery({id}:{id:number}){
 const f=useFlow();const {items}=useMuseum();const r=rooms[id-1];const [detail,setDetail]=useState<Item|null>(null);
 return <><MobileScroll className={`museum-scroll ${id===3?'gallery-dark':''}`}><main className="gallery"><div className="gallery-intro pad"><small>{n(id)} · {id===3?'하이라이트':'일반 전시'}</small><h1>{r.name}</h1><p>{r.desc}</p></div>{items.filter(x=>x.room===id).map((x,i)=><article className={`exhibit exhibit-${x.kind}`} key={x.id}>{x.image&&<img className={id===3?'spotlight exhibit-image':'exhibit-image'} src={x.image} alt={x.title}/>}<div className="exhibit-copy"><small>소장품 {n(i+1)} · {x.kind==='photo'?'사진':x.kind==='text'?'문장':x.demo?'음악':'링크'}</small>{x.text?<blockquote>{x.text}</blockquote>:<h2>{x.title}</h2>}<p>{x.note}</p>{x.url&&<a className="text-link" href={x.url} target="_blank" rel="noreferrer">원본 링크 열기 <ArrowRightIcon/></a>}{x.kind==='link'&&x.demo&&<p className="prototype-note">예시 앨범 · 음원 연결 전</p>}<button className="text-link" onClick={()=>setDetail(x)}>기록 펼쳐보기 <ArrowRightIcon/></button>{x.demo&&<em>예시 소장품</em>}</div></article>)}<div className="pad"><button className="secondary" onClick={()=>f.replace(lobby())}>다른 전시실 둘러보기 <ArrowRightIcon/></button></div></main></MobileScroll><BottomSheet open={!!detail} onOpenChange={open=>!open&&setDetail(null)} title={detail?.title||'소장품 기록'} description="소장품에 담긴 나의 이야기" snap={.7}>{detail&&<div className="detail-content">{detail.image&&<img src={detail.image} alt={detail.title}/>} {detail.text&&<blockquote>{detail.text}</blockquote>}<p>{detail.note||'아직 남긴 이야기가 없어요.'}</p>{detail.url&&<a href={detail.url} target="_blank" rel="noreferrer">{detail.url}</a>}<button className="secondary" onClick={()=>setDetail(null)}>전시로 돌아가기</button></div>}</BottomSheet></>;
}
function Thumb({x}:{x:Item}){return x.image?<img src={x.image} alt=""/>:<div className="text-thumb">{x.text||x.title}</div>}
function Inbox(){const f=useFlow();const {items,place,toast}=useMuseum();const waiting=items.filter(x=>x.room===null);const [selected,setSelected]=useState<string[]>([]);const [room,setRoom]=useState(1);const toggle=(id:string)=>setSelected(v=>v.includes(id)?v.filter(x=>x!==id):[...v,id]);return <MobileScroll className="museum-scroll"><main className="inbox pad"><div className="page-heading"><h1>수집함</h1><p>아직 전시실을 정하지 않은 소장품이에요.</p></div><div className="inbox-toolbar"><span>소장품 {waiting.length}개</span><button onClick={()=>setSelected(selected.length===waiting.length?[]:waiting.map(x=>x.id))}>전체 선택</button></div>{waiting.map(x=><button className="inbox-row" role="checkbox" aria-checked={selected.includes(x.id)} key={x.id} onClick={()=>toggle(x.id)}><Thumb x={x}/><span><b>{x.title}</b><small>{x.kind==='photo'?'사진':x.kind==='text'?'문장':'음악 · 링크'}</small></span><i className={selected.includes(x.id)?'checked':''}>{selected.includes(x.id)&&<CheckIcon/>}</i></button>)}<section className="placement"><h2>{selected.length}개 선택됨</h2><label>배치할 전시실</label><select value={room} onChange={e=>setRoom(Number(e.target.value))}>{rooms.map(r=><option key={r.id} value={r.id}>{n(r.id)}　{r.name}</option>)}</select><p>선택한 소장품을 이 전시실에 배치합니다.</p><button className="primary" disabled={!selected.length} onClick={()=>{place(selected,room);toast(`${selected.length}개 소장품을 전시했어요.`);setSelected([]);f.push(gallery(room))}}>{selected.length?`${selected.length}개 전시하기`:'전시할 소장품을 선택해주세요'}</button></section></main></MobileScroll>}
function RoomPicker({value,onChange,optional=false}:{value:number|null;onChange:(id:number|null)=>void;optional?:boolean}){
 const [open,setOpen]=useState(false);
 return <><button className="room-select" onClick={()=>setOpen(true)} aria-label="배치할 전시실"><span>{value?`${n(value)}　${rooms[value-1].name}`:'나중에 정하기'}</span><ChevronDownIcon/></button><BottomSheet open={open} onOpenChange={setOpen} title="전시실 선택" description="소장품을 전시할 방을 골라주세요." snap={.58}><div className="room-picker">{optional&&<button onClick={()=>{onChange(null);setOpen(false)}}>나중에 정하기 {value===null&&<CheckIcon/>}</button>}{rooms.map(r=><button key={r.id} onClick={()=>{onChange(r.id);setOpen(false)}}>{n(r.id)}　{r.name}{value===r.id&&<CheckIcon/>}</button>)}</div></BottomSheet></>;
}
function Add(){
 const f=useFlow();const {add,toast}=useMuseum();
 const [kind,setKind]=useState<Kind>('photo');const [photo,setPhoto]=useState('');const [title,setTitle]=useState('');const [note,setNote]=useState('');const [text,setText]=useState('');const [url,setUrl]=useState('');const [room,setRoom]=useState<number|null>(null);const [error,setError]=useState('');const file=useRef<HTMLInputElement>(null);
 function save(){
  let safeUrl='';
  if(kind==='photo'&&!photo){setError('사진을 선택하거나 예시 사진을 사용해주세요.');return}
  if(kind==='text'&&!text.trim()){setError('담고 싶은 문장이나 메모를 적어주세요.');return}
  if(kind==='link'){try{const parsed=new URL(url.trim());if(!['http:','https:'].includes(parsed.protocol))throw Error();safeUrl=parsed.href}catch{setError('https://로 시작하는 올바른 링크를 입력해주세요.');return}}
  const fallback=kind==='text'?text.trim().slice(0,24):kind==='link'?new URL(safeUrl).hostname:'이름 없는 사진';
  add({id:crypto.randomUUID(),kind,title:title.trim()||fallback,note:note.trim(),room,image:kind==='photo'?photo:undefined,text:kind==='text'?text.trim():undefined,url:safeUrl||undefined});
  toast(room?'전시실에 소장품을 담았어요.':'수집함에 소장품을 담았어요.');f.replace(room?gallery(room):inbox());
 }
 return <MobileScroll className="museum-scroll"><main className="add-page pad"><div className="page-heading"><h1>마음에 남은 것을 담아요</h1><p>먼저 담아두고, 설명은 나중에 적어도 좋아요.</p></div><div className="input-tabs" role="tablist" aria-label="소장품 종류">{([['photo','사진',ImageIcon],['text','문장 · 메모',TextIcon],['link','링크',Link2Icon]] as const).map(([v,l,I])=><button role="tab" aria-selected={kind===v} className={kind===v?'active':''} key={v} onClick={()=>{setKind(v);setError('')}}><I/>{l}</button>)}</div>
 {kind==='photo'&&<><input ref={file} type="file" accept="image/*" hidden aria-label="사진 파일" onChange={e=>{const image=e.target.files?.[0];if(!image)return;if(!image.type.startsWith('image/')){setError('이미지 파일을 선택해주세요.');return}setPhoto(URL.createObjectURL(image));setError('')}}/>{photo?<><img className="upload-preview" src={photo} alt="추가할 사진 미리보기"/><div className="upload-caption"><span>사진 1장</span><button onClick={()=>file.current?.click()}>바꾸기</button></div></>:<div className="upload-empty"><ImageIcon/><p>사진을 담아보세요.</p><button className="secondary" onClick={()=>file.current?.click()}>사진 선택</button><button className="text-link" onClick={()=>{setPhoto(a('rain.png'));setError('')}}>예시 사진으로 체험하기</button></div>}</>}
 {kind==='text'&&<label className="field">문장 · 메모<KeyboardTextarea value={text} onChange={e=>setText(e.target.value)} placeholder="기억하고 싶은 문장이나 순간" rows={4}/></label>}
 {kind==='link'&&<label className="field">음악 · 영상 · 웹페이지 링크<KeyboardInput type="url" value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://"/><small>원본 링크로 저장해요.</small></label>}
 <label className="field">제목 <small>· 선택</small><KeyboardInput value={title} onChange={e=>setTitle(e.target.value)} placeholder="소장품의 이름"/></label><label className="field">남기고 싶은 이야기 <small>· 선택</small><KeyboardTextarea value={note} onChange={e=>setNote(e.target.value)} placeholder="왜 마음에 들었나요?" rows={3}/></label><div className="field">전시실<RoomPicker value={room} onChange={setRoom} optional/><small>전시실을 정하지 않으면 수집함에 보관돼요.</small></div>{error&&<p className="form-error" role="alert">{error}</p>}<p className="prototype-note">체험용 저장 · 새로고침하면 초기화돼요.</p><button className="primary" onClick={save}>소장품 저장 <CheckIcon/></button></main></MobileScroll>;
}
